/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StartWorkflow,
    StartWorkflowFromJSON,
    StartWorkflowFromJSONTyped,
    StartWorkflowToJSON,
} from './StartWorkflow';
import {
    TaskDetails,
    TaskDetailsFromJSON,
    TaskDetailsFromJSONTyped,
    TaskDetailsToJSON,
} from './TaskDetails';

/**
 * 
 * @export
 * @interface Action
 */
export interface Action {
    /**
     * 
     * @type {string}
     * @memberof Action
     */
    action?: ActionActionEnum;
    /**
     * 
     * @type {StartWorkflow}
     * @memberof Action
     */
    startWorkflow?: StartWorkflow;
    /**
     * 
     * @type {TaskDetails}
     * @memberof Action
     */
    completeTask?: TaskDetails;
    /**
     * 
     * @type {TaskDetails}
     * @memberof Action
     */
    failTask?: TaskDetails;
    /**
     * 
     * @type {boolean}
     * @memberof Action
     */
    expandInlineJSON?: boolean;
}

/**
* @export
* @enum {string}
*/
export enum ActionActionEnum {
    StartWorkflow = 'start_workflow',
    CompleteTask = 'complete_task',
    FailTask = 'fail_task'
}

export function ActionFromJSON(json: any): Action {
    return ActionFromJSONTyped(json, false);
}

export function ActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Action {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': !exists(json, 'action') ? undefined : json['action'],
        'startWorkflow': !exists(json, 'start_workflow') ? undefined : StartWorkflowFromJSON(json['start_workflow']),
        'completeTask': !exists(json, 'complete_task') ? undefined : TaskDetailsFromJSON(json['complete_task']),
        'failTask': !exists(json, 'fail_task') ? undefined : TaskDetailsFromJSON(json['fail_task']),
        'expandInlineJSON': !exists(json, 'expandInlineJSON') ? undefined : json['expandInlineJSON'],
    };
}

export function ActionToJSON(value?: Action | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'start_workflow': StartWorkflowToJSON(value.startWorkflow),
        'complete_task': TaskDetailsToJSON(value.completeTask),
        'fail_task': TaskDetailsToJSON(value.failTask),
        'expandInlineJSON': value.expandInlineJSON,
    };
}

