/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkResponse
 */
export interface BulkResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof BulkResponse
     */
    bulkErrorResults?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkResponse
     */
    bulkSuccessfulResults?: Array<string>;
}

export function BulkResponseFromJSON(json: any): BulkResponse {
    return BulkResponseFromJSONTyped(json, false);
}

export function BulkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bulkErrorResults': !exists(json, 'bulkErrorResults') ? undefined : json['bulkErrorResults'],
        'bulkSuccessfulResults': !exists(json, 'bulkSuccessfulResults') ? undefined : json['bulkSuccessfulResults'],
    };
}

export function BulkResponseToJSON(value?: BulkResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bulkErrorResults': value.bulkErrorResults,
        'bulkSuccessfulResults': value.bulkSuccessfulResults,
    };
}

