/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConductorApplication
 */
export interface ConductorApplication {
    /**
     * 
     * @type {string}
     * @memberof ConductorApplication
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ConductorApplication
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ConductorApplication
     */
    createdBy?: string;
}

export function ConductorApplicationFromJSON(json: any): ConductorApplication {
    return ConductorApplicationFromJSONTyped(json, false);
}

export function ConductorApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConductorApplication {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
    };
}

export function ConductorApplicationToJSON(value?: ConductorApplication | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'createdBy': value.createdBy,
    };
}

