/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrUpdateApplicationRequest
 */
export interface CreateOrUpdateApplicationRequest {
    /**
     * Application's name e.g.: Payment Processors
     * @type {string}
     * @memberof CreateOrUpdateApplicationRequest
     */
    name: string;
}

export function CreateOrUpdateApplicationRequestFromJSON(json: any): CreateOrUpdateApplicationRequest {
    return CreateOrUpdateApplicationRequestFromJSONTyped(json, false);
}

export function CreateOrUpdateApplicationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrUpdateApplicationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateOrUpdateApplicationRequestToJSON(value?: CreateOrUpdateApplicationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

