/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExternalStorageLocation
 */
export interface ExternalStorageLocation {
    /**
     * 
     * @type {string}
     * @memberof ExternalStorageLocation
     */
    uri?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalStorageLocation
     */
    path?: string;
}

export function ExternalStorageLocationFromJSON(json: any): ExternalStorageLocation {
    return ExternalStorageLocationFromJSONTyped(json, false);
}

export function ExternalStorageLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalStorageLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uri': !exists(json, 'uri') ? undefined : json['uri'],
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function ExternalStorageLocationToJSON(value?: ExternalStorageLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uri': value.uri,
        'path': value.path,
    };
}

