/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateTokenRequest
 */
export interface GenerateTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof GenerateTokenRequest
     */
    keyId: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateTokenRequest
     */
    keySecret: string;
}

export function GenerateTokenRequestFromJSON(json: any): GenerateTokenRequest {
    return GenerateTokenRequestFromJSONTyped(json, false);
}

export function GenerateTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateTokenRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'keyId': json['keyId'],
        'keySecret': json['keySecret'],
    };
}

export function GenerateTokenRequestToJSON(value?: GenerateTokenRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'keyId': value.keyId,
        'keySecret': value.keySecret,
    };
}

