/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConductorUser,
    ConductorUserFromJSON,
    ConductorUserFromJSONTyped,
    ConductorUserToJSON,
} from './ConductorUser';
import {
    TaskDef,
    TaskDefFromJSON,
    TaskDefFromJSONTyped,
    TaskDefToJSON,
} from './TaskDef';

/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {ConductorUser}
     * @memberof InlineObject
     */
    user?: ConductorUser;
    /**
     * 
     * @type {TaskDef}
     * @memberof InlineObject
     */
    taskDef?: TaskDef;
}

export function InlineObjectFromJSON(json: any): InlineObject {
    return InlineObjectFromJSONTyped(json, false);
}

export function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : ConductorUserFromJSON(json['user']),
        'taskDef': !exists(json, 'taskDef') ? undefined : TaskDefFromJSON(json['taskDef']),
    };
}

export function InlineObjectToJSON(value?: InlineObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': ConductorUserToJSON(value.user),
        'taskDef': TaskDefToJSON(value.taskDef),
    };
}

