/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UpsertGroupRequest,
    UpsertGroupRequestFromJSON,
    UpsertGroupRequestFromJSONTyped,
    UpsertGroupRequestToJSON,
} from './UpsertGroupRequest';

/**
 * 
 * @export
 * @interface InlineObject10
 */
export interface InlineObject10 {
    /**
     * 
     * @type {string}
     * @memberof InlineObject10
     */
    principal?: string;
    /**
     * 
     * @type {UpsertGroupRequest}
     * @memberof InlineObject10
     */
    request?: UpsertGroupRequest;
}

export function InlineObject10FromJSON(json: any): InlineObject10 {
    return InlineObject10FromJSONTyped(json, false);
}

export function InlineObject10FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject10 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'principal': !exists(json, 'principal') ? undefined : json['principal'],
        'request': !exists(json, 'request') ? undefined : UpsertGroupRequestFromJSON(json['request']),
    };
}

export function InlineObject10ToJSON(value?: InlineObject10 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'principal': value.principal,
        'request': UpsertGroupRequestToJSON(value.request),
    };
}

