/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConductorUser,
    ConductorUserFromJSON,
    ConductorUserFromJSONTyped,
    ConductorUserToJSON,
} from './ConductorUser';
import {
    TaskDef,
    TaskDefFromJSON,
    TaskDefFromJSONTyped,
    TaskDefToJSON,
} from './TaskDef';

/**
 * 
 * @export
 * @interface InlineObject1
 */
export interface InlineObject1 {
    /**
     * 
     * @type {ConductorUser}
     * @memberof InlineObject1
     */
    user?: ConductorUser;
    /**
     * 
     * @type {Array<TaskDef>}
     * @memberof InlineObject1
     */
    taskDefs?: Array<TaskDef>;
}

export function InlineObject1FromJSON(json: any): InlineObject1 {
    return InlineObject1FromJSONTyped(json, false);
}

export function InlineObject1FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : ConductorUserFromJSON(json['user']),
        'taskDefs': !exists(json, 'taskDefs') ? undefined : ((json['taskDefs'] as Array<any>).map(TaskDefFromJSON)),
    };
}

export function InlineObject1ToJSON(value?: InlineObject1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': ConductorUserToJSON(value.user),
        'taskDefs': value.taskDefs === undefined ? undefined : ((value.taskDefs as Array<any>).map(TaskDefToJSON)),
    };
}

