/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AuthorizationRequest,
    AuthorizationRequestFromJSON,
    AuthorizationRequestFromJSONTyped,
    AuthorizationRequestToJSON,
} from './AuthorizationRequest';

/**
 * 
 * @export
 * @interface InlineObject5
 */
export interface InlineObject5 {
    /**
     * 
     * @type {string}
     * @memberof InlineObject5
     */
    principal?: string;
    /**
     * 
     * @type {AuthorizationRequest}
     * @memberof InlineObject5
     */
    request?: AuthorizationRequest;
}

export function InlineObject5FromJSON(json: any): InlineObject5 {
    return InlineObject5FromJSONTyped(json, false);
}

export function InlineObject5FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject5 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'principal': !exists(json, 'principal') ? undefined : json['principal'],
        'request': !exists(json, 'request') ? undefined : AuthorizationRequestFromJSON(json['request']),
    };
}

export function InlineObject5ToJSON(value?: InlineObject5 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'principal': value.principal,
        'request': AuthorizationRequestToJSON(value.request),
    };
}

