/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StartWorkflowRequest,
    StartWorkflowRequestFromJSON,
    StartWorkflowRequestFromJSONTyped,
    StartWorkflowRequestToJSON,
} from './StartWorkflowRequest';

/**
 * 
 * @export
 * @interface InlineObject2
 */
export interface InlineObject2 {
    /**
     * 
     * @type {StartWorkflowRequest}
     * @memberof InlineObject2
     */
    request?: StartWorkflowRequest;
    /**
     * 
     * @type {string}
     * @memberof InlineObject2
     */
    userId?: string;
}

export function InlineObject2FromJSON(json: any): InlineObject2 {
    return InlineObject2FromJSONTyped(json, false);
}

export function InlineObject2FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'request': !exists(json, 'request') ? undefined : StartWorkflowRequestFromJSON(json['request']),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function InlineObject2ToJSON(value?: InlineObject2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'request': StartWorkflowRequestToJSON(value.request),
        'userId': value.userId,
    };
}

