/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateOrUpdateApplicationRequest,
    CreateOrUpdateApplicationRequestFromJSON,
    CreateOrUpdateApplicationRequestFromJSONTyped,
    CreateOrUpdateApplicationRequestToJSON,
} from './CreateOrUpdateApplicationRequest';

/**
 * 
 * @export
 * @interface InlineObject8
 */
export interface InlineObject8 {
    /**
     * 
     * @type {string}
     * @memberof InlineObject8
     */
    principal?: string;
    /**
     * 
     * @type {CreateOrUpdateApplicationRequest}
     * @memberof InlineObject8
     */
    request?: CreateOrUpdateApplicationRequest;
}

export function InlineObject8FromJSON(json: any): InlineObject8 {
    return InlineObject8FromJSONTyped(json, false);
}

export function InlineObject8FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject8 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'principal': !exists(json, 'principal') ? undefined : json['principal'],
        'request': !exists(json, 'request') ? undefined : CreateOrUpdateApplicationRequestFromJSON(json['request']),
    };
}

export function InlineObject8ToJSON(value?: InlineObject8 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'principal': value.principal,
        'request': CreateOrUpdateApplicationRequestToJSON(value.request),
    };
}

