/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UpsertUserRequest,
    UpsertUserRequestFromJSON,
    UpsertUserRequestFromJSONTyped,
    UpsertUserRequestToJSON,
} from './UpsertUserRequest';

/**
 * 
 * @export
 * @interface InlineObject11
 */
export interface InlineObject11 {
    /**
     * 
     * @type {string}
     * @memberof InlineObject11
     */
    principal?: string;
    /**
     * 
     * @type {UpsertUserRequest}
     * @memberof InlineObject11
     */
    request?: UpsertUserRequest;
}

export function InlineObject11FromJSON(json: any): InlineObject11 {
    return InlineObject11FromJSONTyped(json, false);
}

export function InlineObject11FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject11 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'principal': !exists(json, 'principal') ? undefined : json['principal'],
        'request': !exists(json, 'request') ? undefined : UpsertUserRequestFromJSON(json['request']),
    };
}

export function InlineObject11ToJSON(value?: InlineObject11 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'principal': value.principal,
        'request': UpsertUserRequestToJSON(value.request),
    };
}

