/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConductorUser,
    ConductorUserFromJSON,
    ConductorUserFromJSONTyped,
    ConductorUserToJSON,
} from './ConductorUser';
import {
    WorkflowDef,
    WorkflowDefFromJSON,
    WorkflowDefFromJSONTyped,
    WorkflowDefToJSON,
} from './WorkflowDef';

/**
 * 
 * @export
 * @interface InlineObject4
 */
export interface InlineObject4 {
    /**
     * 
     * @type {ConductorUser}
     * @memberof InlineObject4
     */
    user?: ConductorUser;
    /**
     * 
     * @type {WorkflowDef}
     * @memberof InlineObject4
     */
    workflowDef?: WorkflowDef;
}

export function InlineObject4FromJSON(json: any): InlineObject4 {
    return InlineObject4FromJSONTyped(json, false);
}

export function InlineObject4FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject4 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : ConductorUserFromJSON(json['user']),
        'workflowDef': !exists(json, 'workflowDef') ? undefined : WorkflowDefFromJSON(json['workflowDef']),
    };
}

export function InlineObject4ToJSON(value?: InlineObject4 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': ConductorUserToJSON(value.user),
        'workflowDef': WorkflowDefToJSON(value.workflowDef),
    };
}

