/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConductorUser,
    ConductorUserFromJSON,
    ConductorUserFromJSONTyped,
    ConductorUserToJSON,
} from './ConductorUser';
import {
    WorkflowDef,
    WorkflowDefFromJSON,
    WorkflowDefFromJSONTyped,
    WorkflowDefToJSON,
} from './WorkflowDef';

/**
 * 
 * @export
 * @interface InlineObject3
 */
export interface InlineObject3 {
    /**
     * 
     * @type {ConductorUser}
     * @memberof InlineObject3
     */
    user?: ConductorUser;
    /**
     * 
     * @type {Array<WorkflowDef>}
     * @memberof InlineObject3
     */
    workflowDefs?: Array<WorkflowDef>;
}

export function InlineObject3FromJSON(json: any): InlineObject3 {
    return InlineObject3FromJSONTyped(json, false);
}

export function InlineObject3FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject3 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : ConductorUserFromJSON(json['user']),
        'workflowDefs': !exists(json, 'workflowDefs') ? undefined : ((json['workflowDefs'] as Array<any>).map(WorkflowDefFromJSON)),
    };
}

export function InlineObject3ToJSON(value?: InlineObject3 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': ConductorUserToJSON(value.user),
        'workflowDefs': value.workflowDefs === undefined ? undefined : ((value.workflowDefs as Array<any>).map(WorkflowDefToJSON)),
    };
}

