/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConductorUser,
    ConductorUserFromJSON,
    ConductorUserFromJSONTyped,
    ConductorUserToJSON,
} from './ConductorUser';
import {
    SaveScheduleRequest,
    SaveScheduleRequestFromJSON,
    SaveScheduleRequestFromJSONTyped,
    SaveScheduleRequestToJSON,
} from './SaveScheduleRequest';

/**
 * 
 * @export
 * @interface InlineObject7
 */
export interface InlineObject7 {
    /**
     * 
     * @type {ConductorUser}
     * @memberof InlineObject7
     */
    user?: ConductorUser;
    /**
     * 
     * @type {string}
     * @memberof InlineObject7
     */
    userId?: string;
    /**
     * 
     * @type {SaveScheduleRequest}
     * @memberof InlineObject7
     */
    request?: SaveScheduleRequest;
}

export function InlineObject7FromJSON(json: any): InlineObject7 {
    return InlineObject7FromJSONTyped(json, false);
}

export function InlineObject7FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject7 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : ConductorUserFromJSON(json['user']),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'request': !exists(json, 'request') ? undefined : SaveScheduleRequestFromJSON(json['request']),
    };
}

export function InlineObject7ToJSON(value?: InlineObject7 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': ConductorUserToJSON(value.user),
        'userId': value.userId,
        'request': SaveScheduleRequestToJSON(value.request),
    };
}

