/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PollData
 */
export interface PollData {
    /**
     * 
     * @type {string}
     * @memberof PollData
     */
    queueName?: string;
    /**
     * 
     * @type {string}
     * @memberof PollData
     */
    domain?: string;
    /**
     * 
     * @type {string}
     * @memberof PollData
     */
    workerId?: string;
    /**
     * 
     * @type {number}
     * @memberof PollData
     */
    lastPollTime?: number;
}

export function PollDataFromJSON(json: any): PollData {
    return PollDataFromJSONTyped(json, false);
}

export function PollDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PollData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'queueName': !exists(json, 'queueName') ? undefined : json['queueName'],
        'domain': !exists(json, 'domain') ? undefined : json['domain'],
        'workerId': !exists(json, 'workerId') ? undefined : json['workerId'],
        'lastPollTime': !exists(json, 'lastPollTime') ? undefined : json['lastPollTime'],
    };
}

export function PollDataToJSON(value?: PollData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'queueName': value.queueName,
        'domain': value.domain,
        'workerId': value.workerId,
        'lastPollTime': value.lastPollTime,
    };
}

