/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RerunWorkflowRequest
 */
export interface RerunWorkflowRequest {
    /**
     * 
     * @type {string}
     * @memberof RerunWorkflowRequest
     */
    reRunFromWorkflowId?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof RerunWorkflowRequest
     */
    workflowInput?: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof RerunWorkflowRequest
     */
    reRunFromTaskId?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof RerunWorkflowRequest
     */
    taskInput?: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof RerunWorkflowRequest
     */
    correlationId?: string;
}

export function RerunWorkflowRequestFromJSON(json: any): RerunWorkflowRequest {
    return RerunWorkflowRequestFromJSONTyped(json, false);
}

export function RerunWorkflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RerunWorkflowRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reRunFromWorkflowId': !exists(json, 'reRunFromWorkflowId') ? undefined : json['reRunFromWorkflowId'],
        'workflowInput': !exists(json, 'workflowInput') ? undefined : json['workflowInput'],
        'reRunFromTaskId': !exists(json, 'reRunFromTaskId') ? undefined : json['reRunFromTaskId'],
        'taskInput': !exists(json, 'taskInput') ? undefined : json['taskInput'],
        'correlationId': !exists(json, 'correlationId') ? undefined : json['correlationId'],
    };
}

export function RerunWorkflowRequestToJSON(value?: RerunWorkflowRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reRunFromWorkflowId': value.reRunFromWorkflowId,
        'workflowInput': value.workflowInput,
        'reRunFromTaskId': value.reRunFromTaskId,
        'taskInput': value.taskInput,
        'correlationId': value.correlationId,
    };
}

