/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TaskSummary,
    TaskSummaryFromJSON,
    TaskSummaryFromJSONTyped,
    TaskSummaryToJSON,
} from './TaskSummary';

/**
 * 
 * @export
 * @interface SearchResultTaskSummary
 */
export interface SearchResultTaskSummary {
    /**
     * 
     * @type {number}
     * @memberof SearchResultTaskSummary
     */
    totalHits?: number;
    /**
     * 
     * @type {Array<TaskSummary>}
     * @memberof SearchResultTaskSummary
     */
    results?: Array<TaskSummary>;
}

export function SearchResultTaskSummaryFromJSON(json: any): SearchResultTaskSummary {
    return SearchResultTaskSummaryFromJSONTyped(json, false);
}

export function SearchResultTaskSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultTaskSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalHits': !exists(json, 'totalHits') ? undefined : json['totalHits'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(TaskSummaryFromJSON)),
    };
}

export function SearchResultTaskSummaryToJSON(value?: SearchResultTaskSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalHits': value.totalHits,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(TaskSummaryToJSON)),
    };
}

