/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    WorkflowSummary,
    WorkflowSummaryFromJSON,
    WorkflowSummaryFromJSONTyped,
    WorkflowSummaryToJSON,
} from './WorkflowSummary';

/**
 * 
 * @export
 * @interface SearchResultWorkflowSummary
 */
export interface SearchResultWorkflowSummary {
    /**
     * 
     * @type {number}
     * @memberof SearchResultWorkflowSummary
     */
    totalHits?: number;
    /**
     * 
     * @type {Array<WorkflowSummary>}
     * @memberof SearchResultWorkflowSummary
     */
    results?: Array<WorkflowSummary>;
}

export function SearchResultWorkflowSummaryFromJSON(json: any): SearchResultWorkflowSummary {
    return SearchResultWorkflowSummaryFromJSONTyped(json, false);
}

export function SearchResultWorkflowSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultWorkflowSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalHits': !exists(json, 'totalHits') ? undefined : json['totalHits'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(WorkflowSummaryFromJSON)),
    };
}

export function SearchResultWorkflowSummaryToJSON(value?: SearchResultWorkflowSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalHits': value.totalHits,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(WorkflowSummaryToJSON)),
    };
}

