/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    WorkflowScheduleExecutionModel,
    WorkflowScheduleExecutionModelFromJSON,
    WorkflowScheduleExecutionModelFromJSONTyped,
    WorkflowScheduleExecutionModelToJSON,
} from './WorkflowScheduleExecutionModel';

/**
 * 
 * @export
 * @interface SearchResultWorkflowScheduleExecutionModel
 */
export interface SearchResultWorkflowScheduleExecutionModel {
    /**
     * 
     * @type {number}
     * @memberof SearchResultWorkflowScheduleExecutionModel
     */
    totalHits?: number;
    /**
     * 
     * @type {Array<WorkflowScheduleExecutionModel>}
     * @memberof SearchResultWorkflowScheduleExecutionModel
     */
    results?: Array<WorkflowScheduleExecutionModel>;
}

export function SearchResultWorkflowScheduleExecutionModelFromJSON(json: any): SearchResultWorkflowScheduleExecutionModel {
    return SearchResultWorkflowScheduleExecutionModelFromJSONTyped(json, false);
}

export function SearchResultWorkflowScheduleExecutionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultWorkflowScheduleExecutionModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalHits': !exists(json, 'totalHits') ? undefined : json['totalHits'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(WorkflowScheduleExecutionModelFromJSON)),
    };
}

export function SearchResultWorkflowScheduleExecutionModelToJSON(value?: SearchResultWorkflowScheduleExecutionModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalHits': value.totalHits,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(WorkflowScheduleExecutionModelToJSON)),
    };
}

