/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Task,
    TaskFromJSON,
    TaskFromJSONTyped,
    TaskToJSON,
} from './Task';

/**
 * 
 * @export
 * @interface SearchResultTask
 */
export interface SearchResultTask {
    /**
     * 
     * @type {number}
     * @memberof SearchResultTask
     */
    totalHits?: number;
    /**
     * 
     * @type {Array<Task>}
     * @memberof SearchResultTask
     */
    results?: Array<Task>;
}

export function SearchResultTaskFromJSON(json: any): SearchResultTask {
    return SearchResultTaskFromJSONTyped(json, false);
}

export function SearchResultTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultTask {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalHits': !exists(json, 'totalHits') ? undefined : json['totalHits'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(TaskFromJSON)),
    };
}

export function SearchResultTaskToJSON(value?: SearchResultTask | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalHits': value.totalHits,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(TaskToJSON)),
    };
}

