/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SkipTaskRequest
 */
export interface SkipTaskRequest {
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof SkipTaskRequest
     */
    taskInput?: { [key: string]: object; };
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof SkipTaskRequest
     */
    taskOutput?: { [key: string]: object; };
}

export function SkipTaskRequestFromJSON(json: any): SkipTaskRequest {
    return SkipTaskRequestFromJSONTyped(json, false);
}

export function SkipTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkipTaskRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskInput': !exists(json, 'taskInput') ? undefined : json['taskInput'],
        'taskOutput': !exists(json, 'taskOutput') ? undefined : json['taskOutput'],
    };
}

export function SkipTaskRequestToJSON(value?: SkipTaskRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'taskInput': value.taskInput,
        'taskOutput': value.taskOutput,
    };
}

