/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartWorkflow
 */
export interface StartWorkflow {
    /**
     * 
     * @type {string}
     * @memberof StartWorkflow
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof StartWorkflow
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof StartWorkflow
     */
    correlationId?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof StartWorkflow
     */
    input?: { [key: string]: object; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof StartWorkflow
     */
    taskToDomain?: { [key: string]: string; };
}

export function StartWorkflowFromJSON(json: any): StartWorkflow {
    return StartWorkflowFromJSONTyped(json, false);
}

export function StartWorkflowFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartWorkflow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'correlationId': !exists(json, 'correlationId') ? undefined : json['correlationId'],
        'input': !exists(json, 'input') ? undefined : json['input'],
        'taskToDomain': !exists(json, 'taskToDomain') ? undefined : json['taskToDomain'],
    };
}

export function StartWorkflowToJSON(value?: StartWorkflow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'version': value.version,
        'correlationId': value.correlationId,
        'input': value.input,
        'taskToDomain': value.taskToDomain,
    };
}

