/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * User, group or role which is granted/removed access
 * @export
 * @interface SubjectRef
 */
export interface SubjectRef {
    /**
     * User, role or group
     * @type {string}
     * @memberof SubjectRef
     */
    type?: SubjectRefTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SubjectRef
     */
    id: string;
}

/**
* @export
* @enum {string}
*/
export enum SubjectRefTypeEnum {
    User = 'USER',
    Role = 'ROLE',
    Group = 'GROUP'
}

export function SubjectRefFromJSON(json: any): SubjectRef {
    return SubjectRefFromJSONTyped(json, false);
}

export function SubjectRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectRef {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'id': json['id'],
    };
}

export function SubjectRefToJSON(value?: SubjectRef | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

