/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The object over which access is being granted or removed
 * @export
 * @interface TargetRef
 */
export interface TargetRef {
    /**
     * 
     * @type {string}
     * @memberof TargetRef
     */
    type: TargetRefTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TargetRef
     */
    id: TargetRefIdEnum;
}

/**
* @export
* @enum {string}
*/
export enum TargetRefTypeEnum {
    WorkflowDef = 'WORKFLOW_DEF',
    TaskDef = 'TASK_DEF',
    Application = 'APPLICATION',
    User = 'USER'
}/**
* @export
* @enum {string}
*/
export enum TargetRefIdEnum {
    IdentifierOfTheTargetEGNameInCaseItsAWorkflowDef = 'Identifier of the target e.g. `name` in case it\'s a WORKFLOW_DEF'
}

export function TargetRefFromJSON(json: any): TargetRef {
    return TargetRefFromJSONTyped(json, false);
}

export function TargetRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetRef {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function TargetRefToJSON(value?: TargetRef | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

