/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskDetails
 */
export interface TaskDetails {
    /**
     * 
     * @type {string}
     * @memberof TaskDetails
     */
    workflowId?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskDetails
     */
    taskRefName?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof TaskDetails
     */
    output?: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof TaskDetails
     */
    taskId?: string;
}

export function TaskDetailsFromJSON(json: any): TaskDetails {
    return TaskDetailsFromJSONTyped(json, false);
}

export function TaskDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'workflowId': !exists(json, 'workflowId') ? undefined : json['workflowId'],
        'taskRefName': !exists(json, 'taskRefName') ? undefined : json['taskRefName'],
        'output': !exists(json, 'output') ? undefined : json['output'],
        'taskId': !exists(json, 'taskId') ? undefined : json['taskId'],
    };
}

export function TaskDetailsToJSON(value?: TaskDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'workflowId': value.workflowId,
        'taskRefName': value.taskRefName,
        'output': value.output,
        'taskId': value.taskId,
    };
}

