/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpsertGroupRequest
 */
export interface UpsertGroupRequest {
    /**
     * A general description of the group
     * @type {string}
     * @memberof UpsertGroupRequest
     */
    description: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof UpsertGroupRequest
     */
    roles?: UpsertGroupRequestRolesEnum;
}

/**
* @export
* @enum {string}
*/
export enum UpsertGroupRequestRolesEnum {
    Admin = 'ADMIN',
    User = 'USER',
    Worker = 'WORKER',
    MetadataManager = 'METADATA_MANAGER',
    WorkflowManager = 'WORKFLOW_MANAGER'
}

export function UpsertGroupRequestFromJSON(json: any): UpsertGroupRequest {
    return UpsertGroupRequestFromJSONTyped(json, false);
}

export function UpsertGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertGroupRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'roles': !exists(json, 'roles') ? undefined : json['roles'],
    };
}

export function UpsertGroupRequestToJSON(value?: UpsertGroupRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'roles': value.roles,
    };
}

