/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StartWorkflowRequest,
    StartWorkflowRequestFromJSON,
    StartWorkflowRequestFromJSONTyped,
    StartWorkflowRequestToJSON,
} from './StartWorkflowRequest';

/**
 * 
 * @export
 * @interface WorkflowSchedule
 */
export interface WorkflowSchedule {
    /**
     * 
     * @type {string}
     * @memberof WorkflowSchedule
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSchedule
     */
    cronExpression?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WorkflowSchedule
     */
    runCatchupScheduleInstances?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WorkflowSchedule
     */
    paused?: boolean;
    /**
     * 
     * @type {StartWorkflowRequest}
     * @memberof WorkflowSchedule
     */
    startWorkflowRequest?: StartWorkflowRequest;
    /**
     * 
     * @type {number}
     * @memberof WorkflowSchedule
     */
    scheduleStartTime?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkflowSchedule
     */
    scheduleEndTime?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkflowSchedule
     */
    createTime?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkflowSchedule
     */
    updatedTime?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSchedule
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSchedule
     */
    updatedBy?: string;
}

export function WorkflowScheduleFromJSON(json: any): WorkflowSchedule {
    return WorkflowScheduleFromJSONTyped(json, false);
}

export function WorkflowScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowSchedule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'cronExpression': !exists(json, 'cronExpression') ? undefined : json['cronExpression'],
        'runCatchupScheduleInstances': !exists(json, 'runCatchupScheduleInstances') ? undefined : json['runCatchupScheduleInstances'],
        'paused': !exists(json, 'paused') ? undefined : json['paused'],
        'startWorkflowRequest': !exists(json, 'startWorkflowRequest') ? undefined : StartWorkflowRequestFromJSON(json['startWorkflowRequest']),
        'scheduleStartTime': !exists(json, 'scheduleStartTime') ? undefined : json['scheduleStartTime'],
        'scheduleEndTime': !exists(json, 'scheduleEndTime') ? undefined : json['scheduleEndTime'],
        'createTime': !exists(json, 'createTime') ? undefined : json['createTime'],
        'updatedTime': !exists(json, 'updatedTime') ? undefined : json['updatedTime'],
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'updatedBy': !exists(json, 'updatedBy') ? undefined : json['updatedBy'],
    };
}

export function WorkflowScheduleToJSON(value?: WorkflowSchedule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'cronExpression': value.cronExpression,
        'runCatchupScheduleInstances': value.runCatchupScheduleInstances,
        'paused': value.paused,
        'startWorkflowRequest': StartWorkflowRequestToJSON(value.startWorkflowRequest),
        'scheduleStartTime': value.scheduleStartTime,
        'scheduleEndTime': value.scheduleEndTime,
        'createTime': value.createTime,
        'updatedTime': value.updatedTime,
        'createdBy': value.createdBy,
        'updatedBy': value.updatedBy,
    };
}

