/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkflowSummary
 */
export interface WorkflowSummary {
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    workflowType?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowSummary
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    workflowId?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    correlationId?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    updateTime?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    endTime?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    status?: WorkflowSummaryStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    input?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    output?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    reasonForIncompletion?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowSummary
     */
    executionTime?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    event?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    failedReferenceTaskNames?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    externalInputPayloadStoragePath?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    externalOutputPayloadStoragePath?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowSummary
     */
    priority?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSummary
     */
    createdBy?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowSummary
     */
    outputSize?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkflowSummary
     */
    inputSize?: number;
}

/**
* @export
* @enum {string}
*/
export enum WorkflowSummaryStatusEnum {
    Running = 'RUNNING',
    Completed = 'COMPLETED',
    Failed = 'FAILED',
    TimedOut = 'TIMED_OUT',
    Terminated = 'TERMINATED',
    Paused = 'PAUSED'
}

export function WorkflowSummaryFromJSON(json: any): WorkflowSummary {
    return WorkflowSummaryFromJSONTyped(json, false);
}

export function WorkflowSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'workflowType': !exists(json, 'workflowType') ? undefined : json['workflowType'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'workflowId': !exists(json, 'workflowId') ? undefined : json['workflowId'],
        'correlationId': !exists(json, 'correlationId') ? undefined : json['correlationId'],
        'startTime': !exists(json, 'startTime') ? undefined : json['startTime'],
        'updateTime': !exists(json, 'updateTime') ? undefined : json['updateTime'],
        'endTime': !exists(json, 'endTime') ? undefined : json['endTime'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'input': !exists(json, 'input') ? undefined : json['input'],
        'output': !exists(json, 'output') ? undefined : json['output'],
        'reasonForIncompletion': !exists(json, 'reasonForIncompletion') ? undefined : json['reasonForIncompletion'],
        'executionTime': !exists(json, 'executionTime') ? undefined : json['executionTime'],
        'event': !exists(json, 'event') ? undefined : json['event'],
        'failedReferenceTaskNames': !exists(json, 'failedReferenceTaskNames') ? undefined : json['failedReferenceTaskNames'],
        'externalInputPayloadStoragePath': !exists(json, 'externalInputPayloadStoragePath') ? undefined : json['externalInputPayloadStoragePath'],
        'externalOutputPayloadStoragePath': !exists(json, 'externalOutputPayloadStoragePath') ? undefined : json['externalOutputPayloadStoragePath'],
        'priority': !exists(json, 'priority') ? undefined : json['priority'],
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'outputSize': !exists(json, 'outputSize') ? undefined : json['outputSize'],
        'inputSize': !exists(json, 'inputSize') ? undefined : json['inputSize'],
    };
}

export function WorkflowSummaryToJSON(value?: WorkflowSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'workflowType': value.workflowType,
        'version': value.version,
        'workflowId': value.workflowId,
        'correlationId': value.correlationId,
        'startTime': value.startTime,
        'updateTime': value.updateTime,
        'endTime': value.endTime,
        'status': value.status,
        'input': value.input,
        'output': value.output,
        'reasonForIncompletion': value.reasonForIncompletion,
        'executionTime': value.executionTime,
        'event': value.event,
        'failedReferenceTaskNames': value.failedReferenceTaskNames,
        'externalInputPayloadStoragePath': value.externalInputPayloadStoragePath,
        'externalOutputPayloadStoragePath': value.externalOutputPayloadStoragePath,
        'priority': value.priority,
        'createdBy': value.createdBy,
        'outputSize': value.outputSize,
        'inputSize': value.inputSize,
    };
}

