/* tslint:disable */
/* eslint-disable */
/**
 * Conductor API Server
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class MigrationResourceApi extends runtime.BaseAPI {

    /**
     * Migrate Workflow and Task Definitions to Postgres
     */
    async migrateMetadataRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Authorization"] = this.configuration.apiKey("X-Authorization"); // api_key authentication
        }

        const response = await this.request({
            path: `/api/admin/migrate_metadata`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Migrate Workflow and Task Definitions to Postgres
     */
    async migrateMetadata(initOverrides?: RequestInit): Promise<void> {
        await this.migrateMetadataRaw(initOverrides);
    }

    /**
     * Migrate workflows from Redis to Postgres
     */
    async migrateWorkflowsRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Authorization"] = this.configuration.apiKey("X-Authorization"); // api_key authentication
        }

        const response = await this.request({
            path: `/api/admin/migrate_workflow`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Migrate workflows from Redis to Postgres
     */
    async migrateWorkflows(initOverrides?: RequestInit): Promise<number> {
        const response = await this.migrateWorkflowsRaw(initOverrides);
        return await response.value();
    }

}
